version: "3"
services:
  app:
    container_name: school-api
    restart: always
    build: .
    ports:
      - "9050:4000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
